<?php


global $strImagePath;
global $strDBHost;
global $strDBName;
global $strDBUser;
global $strDBPassword;

// Geben Sie hier den Pfad zum Ordner ARTICLEIMAGES an
$strImagePath = "articleimages/";

// Geben Sie hier den Hostname/IP-Adresse des MySQL-Servers an
$strDBHost = "localhost";

// Geben Sie hier den Namen der zu verwendenden SQL-Datenbank an
$strDBName = "30361_webshop";

// Geben Sie hier den Username für den Datenbankzugriff an
$strDBUser = "30361_webshop";

// Geben Sie hier das Passwort für den Datenbankzugriff an
$strDBPassword = "CaseStudy10";

// Standard Bild für unbekannte Artikel
$strDefaultImage = "images/products/mouse1.jpg";

// Standard Währung
$strCurrency = "CHF";

// E-Mail Vorlage für die Auftragsbestätigung
$strEmailTemplate = '/templates/emailTemplate.txt';


?>
